CREATE TABLE kelurahans(id bigint,kecamatan VARCHAR(120),kelurahan VARCHAR(120));
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (1,'Biringkanaya','Bakung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (2,'Biringkanaya','Berua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (3,'Biringkanaya','Bulurokeng');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (4,'Biringkanaya','Daya ');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (5,'Biringkanaya','Katimbang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (6,'Biringkanaya','Laikang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (7,'Biringkanaya','Paccerakkang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (8,'Biringkanaya','Pai');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (9,'Biringkanaya','Sudiang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (10,'Biringkanaya','Sudiang Raya ');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (11,'Biringkanaya','Untia');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (12,'Bontoala','Baraya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (13,'Bontoala','Bontoala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (14,'Bontoala','Bontoala Parang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (15,'Bontoala','Bontoala Tua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (16,'Bontoala','Bunga Ejaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (17,'Bontoala','Gaddong');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (18,'Bontoala','Layang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (19,'Bontoala','Malimongan Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (20,'Bontoala','Parang Layang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (21,'Bontoala','Timungan Lompoa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (22,'Bontoala','Tompo Balang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (23,'Bontoala','Wajo Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (24,'Kepulauan Sangkarrang','Barrang Caddi');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (25,'Kepulauan Sangkarrang','Barrang Lompo');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (26,'Kepulauan Sangkarrang','Kodingareng');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (27,'Makassar','Bara-Baraya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (28,'Makassar','Bara-Baraya Selatan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (29,'Makassar','Bara-Baraya Timur');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (30,'Makassar','Bara-Baraya Utara');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (31,'Makassar','Barana');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (32,'Makassar','Lariang Bangi');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (33,'Makassar','Maccini');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (34,'Makassar','Maccini Gusung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (35,'Makassar','Maacini Parang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (36,'Makassar','Maradekaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (37,'Makassar','Maradekaya Selatan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (38,'Makassar','Maradekaya Utara');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (39,'Makassar','Maricaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (40,'Makassar','Maricaya Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (41,'Mamajang','Baji Mappakasunggu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (42,'Mamajang','Bonto Biraeng');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (43,'Mamajang','Bonto Lebang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (44,'Mamajang','Karang Anyar');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (45,'Mamajang','Labuang Baji');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (46,'Mamajang','Mamajang Dalam');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (47,'Mamajang','Mamajang Luar');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (48,'Mamajang','Mandala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (49,'Mamajang','Maricaya Selatan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (50,'Mamajang',"Pa'batang");
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (51,'Mamajang','Parang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (52,'Mamajang','Sambung Jawa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (53,'Mamajang','Tamparang Keke');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (54,'Manggala','Antang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (55,'Manggala','Bangkala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (56,'Manggala','Batua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (57,'Manggala','Biring Romang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (58,'Manggala','Bitowa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (59,'Manggala','Borong');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (60,'Manggala','Manggala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (61,'Manggala','Tamangapa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (62,'Mariso','Bontorannu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (63,'Mariso','Kampung Buyang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (64,'Mariso','Kunjung Mae');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (65,'Mariso','Lette');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (66,'Mariso','Mario');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (67,'Mariso','Mariso');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (68,'Mariso','Mattoangin');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (69,'Mariso','Panambungan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (70,'Mariso','Tamarunang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (71,'Panakkukang','Karampuang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (72,'Panakkukang','Masale');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (73,'Panakkukang','Pampang ');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (74,'Panakkukang','Panaikang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (75,'Panakkukang','Pandang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (76,'Panakkukang','Sinrijala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (77,'Panakkukang','Tamamaung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (78,'Panakkukang','Karuwisi');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (79,'Panakkukang','Karuwisi Utara');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (80,'Panakkukang','Paropo');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (81,'Panakkukang','Tello Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (82,'Rappocini','Balla Parang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (83,'Rappocini','Banta-Bantaeng');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (84,'Rappocini','Bonto Makkio');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (85,'Rappocini','Bua Kana');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (86,'Rappocini','Gunung Sari');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (87,'Rappocini','Karunrung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (88,'Rappocini','Kassi-Kassi');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (89,'Rappocini','Mapala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (90,'Rappocini','Minasa Upa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (91,'Rappocini','Rappocini');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (92,'Rappocini','Tidung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (93,'Tallo','Buloa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (94,'Tallo','Bunga Eja Beru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (95,'Tallo','Kalukuang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (96,'Tallo','Kaluku Bodoa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (97,'Tallo',"La'latang");
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (98,'Tallo','Lakkang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (99,'Tallo','Lembo');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (100,'Tallo','Pannampu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (101,'Tallo','Rappojawa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (102,'Tallo','Rappokalling');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (103,'Tallo','Suangga');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (104,'Tallo','Tallo');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (105,'Tallo','Tammua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (106,'Tallo','Ujung Pandang Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (107,'Tallo','Wala-Walaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (108,'Tamalanrea','Bira');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (109,'Tamalanrea','Buntusu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (110,'Tamalanrea','Kapasa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (111,'Tamalanrea','Kapasa Raya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (112,'Tamalanrea','Parang Loe');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (113,'Tamalanrea','Tamalanre');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (114,'Tamalanrea','Tamalanrea Indah');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (115,'Tamalanrea','Tamalanrea Raya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (116,'Tamalate','Balang Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (117,'Tamalate','Barombong');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (118,'Tamalate','Bongaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (119,'Tamalate','Bonto Duri');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (120,'Tamalate','Jongaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (121,'Tamalate','Maccini Sombala');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (122,'Tamalate','Mangasa');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (123,'Tamalate','Mannuruki');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (124,'Tamalate',"Pa'baeng-Baeng");
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (125,'Tamalate','Parang Tambung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (126,'Tamalate','Tanjung Merdeka');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (127,'Ujung Pandang','Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (128,'Ujung Pandang','Bulogading');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (129,'Ujung Pandang','Lae-Lae');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (130,'Ujung Pandang','Lajangiru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (131,'Ujung Pandang','Losari');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (132,'Ujung Pandang','Maloku ');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (133,'Ujung Pandang','Mangkura');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (134,'Ujung Pandang','Pisang Selatan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (135,'Ujung Pandang','Pisang Utara');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (136,'Ujung Pandang','Sariwegading');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (137,'Ujung Tanah','Camba Berua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (138,'Ujung Tanah','Cambaya');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (139,'Ujung Tanah','Gusung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (140,'Ujung Tanah','Pattingalloang');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (141,'Ujung Tanah','Pattingalloang Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (142,'Ujung Tanah','Tabaringan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (143,'Ujung Tanah','Tamalabba');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (144,'Ujung Tanah','Totaka');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (145,'Ujung Tanah','Ujung Tanah');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (146,'Wajo','Butung');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (147,'Wajo','Ende');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (148,'Wajo','Malimongan');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (149,'Wajo','Malimongan Tua');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (150,'Wajo','Mampu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (151,'Wajo','Melayu');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (152,'Wajo','Melayu Baru');
INSERT INTO kelurahans (id,kecamatan,kelurahan) VALUES (153,'Wajo','Pattunuang');
